server:
  port: 8080

logging:
  level:
    org.springframework: DEBUG



spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    jdbc-url: jdbc:mysql://localhost:3307/testTodo?serverTimezone=UTC&characterEncoding=UTF-8
    url: jdbc:mysql://localhost:3307/testTodo?serverTimezone=UTC&characterEncoding=UTF-8
    hikari:
      driver-class-name: "com.mysql.cj.jdbc.Driver"
      maximum-pool-size: 20
      connectionTimeout: 30000
      idleTimeout: 600000
      maxLifetime: 1800000
      data-source-properties:
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        useServerPrepStmts: true
    username: root
    password: 1234

  mvc:
    converters.preferred-json-mapper: "gson"
    format.date-time: "yyyy-MM-dd HH:mm:ss"
  gson.date-format: "yyyy-MM-dd HH:mm:ss"
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.MySQL5Dialect


mybatis:
  mapper-locations: "classpath:/mybatis/mapper/**/*.xml"
  type-handlers-package: "com.example.springdemo"
  configuration:
    map-underscore-to-camel-case: true
    default-fetch-size: 100


jpa:
  show-sql: true

management:
  endpoints:
    web:
      exposure:
        include: "*"

